# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - name: Substitute secrets in file action
      # You may pin to the exact commit or the version.
      # uses: faradaytrs/substitute-secrets-action@56a21436cdac9ccc80f882fb96f26941053e644d
      uses: faradaytrs/substitute-secrets-action@2.1
      with:
        # The file or pattern to replace.
        input: './src/environments/environment.ts'
        # A regex to match tokens. Must contain a capturing group.
        substitutionRegex: 'secureToken'
        # JSON representation of the secrets and variables for substitution.
        substitutionData: ${{ secrets.SECURETOKEN }}
    - run: npm run build --if-present
    - name: Upload S3
    # You may pin to the exact commit or the version.
    # uses: shallwefootball/upload-s3-action@4350529f410221787ccf424e50133cbc1b52704e
      uses: shallwefootball/upload-s3-action@v1.3.3
      with:
        # aws key id
        aws_key_id: ${{ secrets.AWS_ACCESS_KEY }}
        # aws secret access key
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # aws bucket name
        aws_bucket: ${{ secrets.AWS_BUCKET }}
        # directory to upload
        source_dir: '/home/runner/work/Website/Website/dist/website'
    
